name: Deploy App to Azure App Services

on:
  push:
    branches:
      - master
      - dev
      - feature/**
      - bug/**
      - release/**
  pull_request:
    branches:
      - master
      - feature/**
      - bug/**
      - release/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifacct for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: springboot-example
          path: ${{ github.workspace }}/target/*.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: springboot-example
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: springboot-app-testing
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: '*.jar'
